### PR TITLE
Update tower icon paths

### LINKED ISSUE #4: outdated icon paths
There are two outdated icon paths:
- presets/landmark/water_tower.svg -->presets/tower/water_tower.svg
- presets/landmark/tower.svg --> presets/tower/tower.svg

### PR DESCRIPTION
**Pull request by don-vip**
Fixes #4

### CODE REVIEW

**Comment by Klumbumbus** [comment]
@DearRude can you please merge this and release a new version of the preset?

**Comment by DearRude** [comment]
Thanks for the PR!

@don-vip Can you also update the zip file as the presets are fetched from it currently?

**Comment by don-vip** [comment]
I didn't see the zip was in the file tree. This is isn't the proper way to go, you should use GitHub zip generated when you perform a release instead. You cannot ask to contributors to modify a binary file when this is not needed.

**Comment by DearRude** [comment]
I also was going with GitHub zip generation at first since it was easier.
However the generated file was way too large because it included /docs.

Also Brazil presets (I assume) had done the same thing with zip generation so I thought that's the norm.
What's your suggestion?

**Comment by don-vip** [comment]
Do you really need it hosted on GitHub? The norm is to simply create it on JOSM website, at https://josm.openstreetmap.de/wiki/Presets You can attach icons to the page, and JOSM infra takes care of everything.

**Comment by DearRude** [comment]
It's easier for me to host it here in order to manage changes and receive suggestions about translation. Maybe I could set up a simple CI to build (make zip) for every release I make on Github and publish the link to JOSM website.

Or I can get rid of /docs directory here since it's not that important anyway.

**Comment by Klumbumbus** [comment]
Could you please proceed?

**Comment by DearRude** [comment]
Sure. I'll do it tomorrow. Sorry for the delay.

**Comment by Klumbumbus** [comment]
You need to increase the version in the xml too, else the users won't get the update.

As the previous link https://raw.githubusercontent.com/DearRude/IranianPresets/master/zip/latast.zip gives an 404 error now, I removed it from https://josm.openstreetmap.de/wiki/PresetsSource?action=diff&version=137. Please add it back once you have a working link.

**Pull request merged**
